/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from '../../common';

export interface CommandMockInterface extends Interface {
  getFunction(nameOrSignature: 'pullInputParam' | 'pushOutputParam'): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'pullInputParam',
    values: [BigNumberish[], BigNumberish, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'pushOutputParam',
    values: [BigNumberish[], BigNumberish, BigNumberish, BigNumberish],
  ): string;

  decodeFunctionResult(functionFragment: 'pullInputParam', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'pushOutputParam', data: BytesLike): Result;
}

export interface CommandMock extends BaseContract {
  connect(runner?: ContractRunner | null): CommandMock;
  waitForDeployment(): Promise<this>;

  interface: CommandMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  pullInputParam: TypedContractMethod<
    [
      callStack: BigNumberish[],
      value: BigNumberish,
      inputMapping: BigNumberish,
      position: BigNumberish,
    ],
    [bigint],
    'view'
  >;

  pushOutputParam: TypedContractMethod<
    [
      callStack: BigNumberish[],
      value: BigNumberish,
      outputMapping: BigNumberish,
      position: BigNumberish,
    ],
    [bigint[]],
    'view'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: 'pullInputParam',
  ): TypedContractMethod<
    [
      callStack: BigNumberish[],
      value: BigNumberish,
      inputMapping: BigNumberish,
      position: BigNumberish,
    ],
    [bigint],
    'view'
  >;
  getFunction(
    nameOrSignature: 'pushOutputParam',
  ): TypedContractMethod<
    [
      callStack: BigNumberish[],
      value: BigNumberish,
      outputMapping: BigNumberish,
      position: BigNumberish,
    ],
    [bigint[]],
    'view'
  >;

  filters: {};
}
