/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BakerFiProxy } from "./BakerFiProxy";
export type { BakerFiProxyAdmin } from "./BakerFiProxyAdmin";
