/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from 'ethers';
import type { Signer, ContractDeployTransaction, ContractRunner } from 'ethers';
import type { NonPayableOverrides } from '../../../common';
import type { MathLibrary, MathLibraryInterface } from '../../../contracts/libraries/MathLibrary';

const _abi = [
  {
    inputs: [],
    name: 'InvalidDivDenominator',
    type: 'error',
  },
  {
    inputs: [],
    name: 'OverflowDetected',
    type: 'error',
  },
] as const;

const _bytecode =
  '0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212203bea45a1eee41341328f99c62f798bf45975ca72a7bf393410f972fda8da758864736f6c63430008180033';

type MathLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MathLibraryConstructorParams,
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MathLibrary__factory extends ContractFactory {
  constructor(...args: MathLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string },
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MathLibrary & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MathLibrary__factory {
    return super.connect(runner) as MathLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MathLibraryInterface {
    return new Interface(_abi) as MathLibraryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MathLibrary {
    return new Contract(address, _abi, runner) as unknown as MathLibrary;
  }
}
