/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type {
  UseTokenActions,
  UseTokenActionsInterface,
} from '../../../../../contracts/core/hooks/UseTokenActions.sol/UseTokenActions';

const _abi = [
  {
    inputs: [],
    name: 'InvalidRecipient',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidToken',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NotEnoughAllowance',
    type: 'error',
  },
  {
    inputs: [],
    name: 'SweepFailed',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint8',
        name: 'version',
        type: 'uint8',
      },
    ],
    name: 'Initialized',
    type: 'event',
  },
] as const;

export class UseTokenActions__factory {
  static readonly abi = _abi;
  static createInterface(): UseTokenActionsInterface {
    return new Interface(_abi) as UseTokenActionsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): UseTokenActions {
    return new Contract(address, _abi, runner) as unknown as UseTokenActions;
  }
}
