/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type RebaseStruct = { elastic: BigNumberish; base: BigNumberish };

export type RebaseStructOutput = [elastic: bigint, base: bigint] & {
  elastic: bigint;
  base: bigint;
};

export interface RebaseLibraryTestInterface extends Interface {
  getFunction(nameOrSignature: "toBase" | "toElastic"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "toBase",
    values: [RebaseStruct, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "toElastic",
    values: [RebaseStruct, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "toBase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "toElastic", data: BytesLike): Result;
}

export interface RebaseLibraryTest extends BaseContract {
  connect(runner?: ContractRunner | null): RebaseLibraryTest;
  waitForDeployment(): Promise<this>;

  interface: RebaseLibraryTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  toBase: TypedContractMethod<
    [total: RebaseStruct, elastic: BigNumberish, roundUp: boolean],
    [bigint],
    "view"
  >;

  toElastic: TypedContractMethod<
    [total: RebaseStruct, base: BigNumberish, roundUp: boolean],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "toBase"
  ): TypedContractMethod<
    [total: RebaseStruct, elastic: BigNumberish, roundUp: boolean],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "toElastic"
  ): TypedContractMethod<
    [total: RebaseStruct, base: BigNumberish, roundUp: boolean],
    [bigint],
    "view"
  >;

  filters: {};
}
