/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers';
import type {
  IERC3156FlashLenderUpgradeable,
  IERC3156FlashLenderUpgradeableInterface,
} from '../../../../@openzeppelin/contracts-upgradeable/interfaces/IERC3156FlashLenderUpgradeable';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'flashFee',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'contract IERC3156FlashBorrowerUpgradeable',
        name: 'receiver',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        internalType: 'bytes',
        name: 'data',
        type: 'bytes',
      },
    ],
    name: 'flashLoan',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
    ],
    name: 'maxFlashLoan',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

export class IERC3156FlashLenderUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): IERC3156FlashLenderUpgradeableInterface {
    return new Interface(_abi) as IERC3156FlashLenderUpgradeableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC3156FlashLenderUpgradeable {
    return new Contract(address, _abi, runner) as unknown as IERC3156FlashLenderUpgradeable;
  }
}
