/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IUniswapV3SwapCallback } from './IUniswapV3SwapCallback';
export type { IV3SwapRouter } from './IV3SwapRouter';
