/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iFlashLoanSol from './IFlashLoan.sol';
export { IProtocolFeesCollector__factory } from './IProtocolFeesCollector__factory';
export { IVault__factory } from './IVault__factory';
