/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC3156FlashBorrower } from "./IERC3156FlashBorrower";
export type { IERC3156FlashLender } from "./IERC3156FlashLender";
export type { IERC4626 } from "./IERC4626";
export type { IERC5267 } from "./IERC5267";
